spring:
  application:
    name: autocreatetable
  jpa:
    database: mysql
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxxx:xxx/xxx?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai
    username: xxxx
    password: xxxx
#set database type if null will use spring.jpa.database
tablecreate:
  dbtype: mysql
